version: '2'
services:
  chat-service:
    environment:
      -  MONGOUSER=${MONGOUSER}
      -  MONGOPWD=${MONGOPWD}
      -  SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    container_name: chat-service
    image: wbfreitas/chat-service:main
    ports:
        - 8080:8080
    networks:
        -  my-bridge 
  cliente-service:
    environment:
      -  MONGOUSER=${MONGOUSER}
      -  MONGOPWD=${MONGOPWD}
      -  SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    container_name: cliente-service
    image: wbfreitas/cliente-service:main
    ports:
        - 8081:8081
    networks:
        -  my-bridge 
  front-chat:
    container_name: front-chat 
    image: wbfreitas/front-chat:main
    ports:
        - 8888:80
    networks:
        -  my-bridge 
networks:
    my-bridge:
        driver: bridge